services:
  - type: web
    name: shivtej-group
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
